/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dev from './dev'
export * as production from './production'
export * as staging from './staging'
export { Erc20__factory } from './Erc20__factory'
